 
### Che mi dia tutte le pizze
GET https://pizza-api-htu2.onrender.com/api/pizza

### CREA UNA PIZZA NUOVA
POST https://pizza-api-htu2.onrender.com/api/pizza
Content-Type: application/json

{
    "name": "Ortolana",
    "price": 8,
    "cover": "/ortolana.webp",
    "ingredients": ["Pomodoro", "Mozzarella", "Melanzane", "Peperoni", "Zucchine"]
}


### CREA UNA PIZZA NUOVA 
POST http://localhost:8080/api/pizza/
Content-Type: application/json

{
    "name": "Gamberi e Rucola",
    "price": 8,
    "cover": "/gamberierucola.webp",
    "ingredients": ["Pomodoro", "Mozzarella", "Gamberi", "Rucola"]
}

### Che mi dia la pizza con id 2
GET http://localhost:8080/api/pizza/

### Che mi dia la pizza con id 2
GET http://localhost:8080/api/pizza/9e18050c-2658-11ef-9c4e-c1b133e9f926

### Che mi dia tutte le pizze con il nome "Margherita"
GET http://localhost:8080/api/pizza?name=Dia

### Che mi dia tutte le pizze con l'ingrediente "Mozzarella"
GET http://localhost:8080/api/pizza?ingredients=Pe